#ifndef _ESK8_BLE_DEFS_H
#define _ESK8_BLE_DEFS_H

#include <esp_gattc_api.h>

#define ESK8_BLE_UUID_AUTH                  0xE8A0
#define ESK8_BLE_UUID_AUTH_KEY              0xE8A1
#define ESK8_BLE_UUID_AUTH_CHANGE           0xE8A2
#define ESK8_BLE_PROP_AUTH                  ( ESP_GATT_CHAR_PROP_BIT_READ )
#define ESK8_BLE_PROP_AUTH_KEY              ( ESP_GATT_CHAR_PROP_BIT_READ | ESP_GATT_CHAR_PROP_BIT_WRITE )
#define ESK8_BLE_PROP_AUTH_CHANGE           ( ESP_GATT_CHAR_PROP_BIT_READ | ESP_GATT_CHAR_PROP_BIT_WRITE )
#define ESK8_BLE_TYPE_AUTH                  ESP_GATT_DB_PRIMARY_SERVICE
#define ESK8_BLE_TYPE_AUTH_KEY              ESP_GATT_DB_CHARACTERISTIC
#define ESK8_BLE_TYPE_AUTH_CHANGE           ESP_GATT_DB_CHARACTERISTIC

#define ESK8_BLE_UUID_CTRL                  0xE8C0
#define ESK8_BLE_UUID_CTRL_SPEED            0xE8C1
#define ESK8_BLE_UUID_CTRL_PWR              0xE8C2
#define ESK8_BLE_PROP_CTRL                  ( ESP_GATT_CHAR_PROP_BIT_READ )
#define ESK8_BLE_PROP_CTRL_SPEED            ( ESP_GATT_CHAR_PROP_BIT_READ | ESP_GATT_CHAR_PROP_BIT_WRITE | ESP_GATT_CHAR_PROP_BIT_NOTIFY )
#define ESK8_BLE_PROP_CTRL_PWR              ( ESP_GATT_CHAR_PROP_BIT_READ | ESP_GATT_CHAR_PROP_BIT_WRITE | ESP_GATT_CHAR_PROP_BIT_NOTIFY )
#define ESK8_BLE_TYPE_CTRL                  ESP_GATT_DB_PRIMARY_SERVICE
#define ESK8_BLE_TYPE_CTRL_SPEED            ESP_GATT_DB_CHARACTERISTIC
#define ESK8_BLE_TYPE_CTRL_PWR              ESP_GATT_DB_CHARACTERISTIC

#define ESK8_BLE_UUID_STATUS                0xE8E0
#define ESK8_BLE_UUID_STATUS_SPEED          0xE8E1
#define ESK8_BLE_UUID_STATUS_BMS_SHALLOW    0xE8E2
#define ESK8_BLE_UUID_STATUS_BMS_DEEP       0xE8E3
#define ESK8_BLE_PROP_STATUS                ( ESP_GATT_CHAR_PROP_BIT_READ |                                ESP_GATT_CHAR_PROP_BIT_NOTIFY )
#define ESK8_BLE_PROP_STATUS_SPEED          ( ESP_GATT_CHAR_PROP_BIT_READ |                                ESP_GATT_CHAR_PROP_BIT_NOTIFY )
#define ESK8_BLE_PROP_STATUS_BMS_SHALLOW    ( ESP_GATT_CHAR_PROP_BIT_READ |                                ESP_GATT_CHAR_PROP_BIT_NOTIFY )
#define ESK8_BLE_PROP_STATUS_BMS_DEEP       ( ESP_GATT_CHAR_PROP_BIT_READ |                                ESP_GATT_CHAR_PROP_BIT_NOTIFY )
#define ESK8_BLE_TYPE_STATUS                ESP_GATT_DB_PRIMARY_SERVICE
#define ESK8_BLE_TYPE_STATUS_SPEED          ESP_GATT_DB_CHARACTERISTIC
#define ESK8_BLE_TYPE_STATUS_BMS_SHALLOW    ESP_GATT_DB_CHARACTERISTIC
#define ESK8_BLE_TYPE_STATUS_BMS_DEEP       ESP_GATT_DB_CHARACTERISTIC


#endif /* _ESK8_BLE_DEFS_H */
