#ifndef _E_SKATE_CONTROLLER_CONFIG_H
#define _E_SKATE_CONTROLLER_CONFIG_H

#define E_SKATE_UART_BMS_UPDATE_MS          50
#define E_SKATE_UART_BMS_MSG_UPDATE_RETRIES 2
#define E_SKATE_UART_BMS_NUM                UART_NUM_1
#define E_SKATE_UART_BMS_TX                 GPIO_NUM_12
#define E_SKATE_UART_BMS_TX_PINS            { GPIO_NUM_25, GPIO_NUM_14, GPIO_NUM_4 , GPIO_NUM_5  }
#define E_SKATE_UART_BMS_RX_PINS            { GPIO_NUM_26, GPIO_NUM_12, GPIO_NUM_16, GPIO_NUM_18 }
#define E_SKATE_UART_BMS_BUFF_SIZE          1000

#endif  /* _E_SKATE_CONTROLLER_CONFIG_H */
