#ifndef _E_SKATE_CONTROLLER_CONFIG_H
#define _E_SKATE_CONTROLLER_CONFIG_H

#define E_SKATE_UART_BMS_TX GPIO_NUM_34
#define E_SKATE_UART_BMS_RX GPIO_NUM_35
#define E_SKATE_UART_BMS_BR 115200


#endif  /* _E_SKATE_CONTROLLER_CONFIG_H */
